Krent dotenv
lev-slinsen/DjangoPizzaShop pull request #17
Opened 2021-05-19 07:04 UTC by demoh2019

2021-05-19 18:45 UTC, ice-ivanov commented on .envPrimer
> +FULL_URL='https://shop.com'
Допиши комментарии. Токен бота рабочий?

2021-05-19 18:48 UTC, ice-ivanov requested changes, later dismissed
Читай коммент

2021-05-20 14:37 UTC, demoh2019 commented
токен рабочий

2021-06-06 13:53 UTC, ice-ivanov approved these changes

2021-06-06 13:54 UTC, merged